### ISSUE TITLE
Vertcoin P2P uses port 5889

### ISSUE THREAD

**Issue by metalicjames** [lukechilds/docker-vertcoind#1]
I notice in the Dockerfile you are exposing port 8333, yet Vertcoin Core uses port 5889 by default for incoming peer to peer connections.

**Comment by lukechilds** [comment]
Are you saying 8333 isn't used at all? Or that 5889 is used as well as 8333?

**Comment by metalicjames** [comment]
I don't think 8333 is used for anything. The two default ports are 5888 for RPC which you set to 8332 in the Dockerfile, and 5889 for peer to peer.

**Comment by ikinsella** [comment]
I can confirm that 8333 and 8332 are unused, I've been using this container in conjunction with a p2pool container which works fine once you replace them with ports 5889 and 5888 respectively.

**Comment by lukechilds** [comment]
Hmmn, weird, because I'm running this in production and it's working.

I didn't think Docker would allow any incoming connections on 5889 without me explicitly allowing it, but it definitely works because I'm fully synced.

Anyway, I'll update to use 5888/5889.

**Comment by lukechilds** [comment]
Updated and pushed to Docker Hub.

Also updated [lukechilds/docker-electrum-vertcoin](https://github.com/lukechilds/docker-electrum-vertcoin).

@metalicjames Thanks for reporting.
