### ISSUE TITLE
I'm writing a docker container for p2pool-vert

### ISSUE THREAD

**Issue by joeknock90** [lukechilds/docker-vertcoind#3]
And I was wondering if i could reference your container in my readme / create a compose file that uses your container as the vertcoind server used to connect. 

Figured I should ask before i just go and do.

**Comment by lukechilds** [comment]
Yeah of course!

It's licensed under MIT, no need to even ask.

**Comment by joeknock90** [comment]
Just didn't want to go throwing stuff around. Thanks for the work you've done here. This is my first container sooooo we'll see how this goes.

**Comment by lukechilds** [comment]
Let me know if you need any help 👍

**Comment by joeknock90** [comment]
Got it working here https://github.com/joeknock90/VertP2PoolDocker

Pretty preliminary but it seems to work. I'm writing up a compose file that uses your container to be used with it. If you have any ideas on how to make it better let me know or better yet FORK!
