### ISSUE TITLE
Which compilation options are necessary?

### ISSUE THREAD

**Issue by dalijolijo** [lukechilds/docker-vertcoind#5]
I want to reuse this electrumx docker solution for other coins, e.g. Bitcore, Bitsend, Bitcloud
Which compilation options are necessary for the coin (vertcoind in vertcoind-v0.14.0-linux-amd64.zip) to run this electrumx docker solution?
Thanks.

**Comment by lukechilds** [comment]
I don't think this question is relevant to the project. This docker container is for Vertcoin, not ElectrumX or any other coin daemon.
